### PR TITLE
[NayNay] Return all info, similar to subkey

### LINKED ISSUE #82: As a user, when I generate a new key, I'd like to have all information about my newly created key
Currently, generating a new key using the CLI produces a single output: the SS58 address of the new account.

```
New account:
{
        name: MyFirstAccount
        address: 5HMnksPMRPqsDqyCj31VoQFgpiswsr12bk2YTyfMUEKCm2bv
        type: seed
}
```

Compare this to Substrate's `subkey` command, which also shows a mnemonic and private information for the generated key:

```
Secret phrase `hotel forest jar hover kite book view eight stuff angle legend defense` is account:
  Secret seed:      0xa05c75731970cc7868a2fb7cb577353cd5b31f62dccced92c441acd8fee0c92d
  Public key (hex): 0xfec70cfbf1977c6965b5af10a4534a6a35d548eb14580594d0bc543286892515
  Account ID:       0xfec70cfbf1977c6965b5af10a4534a6a35d548eb14580594d0bc543286892515
  SS58 Address:     5Hpm9fq3W3dQgwWpAwDS2ZHKAdnk86QRCu7iX4GnmDxycrte
```

What's missing in the CLI output is the secret phrase and the secret seed. Without one (or both?) of those, I feel uncertain about my ability to restore an account key generated by the CLI.

At a minimum, as a user of the CLI, I'd like to have all relevant information about my newly generated key shown to me when I manually create a new account.

### PR DESCRIPTION
**Pull request by rh0delta**
## Related Issue(s)

- Resolves #82

## Proposed Changes

- updated account creation, new or imported, to return all the information a user will need to secure their account
- updated both tui and cli to return the same information

## Testing

- [ ] Unit tests added/updated
- [ ] Integration tests added/updated
- [x] Manual testing performed

## Screenshots (if applicable)

Screenshot 2024-11-15 at 3 00 54 PM
Screenshot 2024-11-15 at 3 01 15 PM

## Checklist

- [x] I have performed a self-review of my code.
- [ ] I have added tests.
- [x] I have commented my code.
- [ ] I have included a `CHANGELOG.md` entry.
- [ ] I have updated documentation in `github.com:entropyxyz/entropy-docs`, where necessary.

### CODE REVIEW

**Comment by johnnymatthews** [comment]
Issue to track in docs here: v

**Comment by johnnymatthews** [comment]
PR ready: https://github.com/entropyxyz/entropy-docs/pull/264

**Review by johnnymatthews — APPROVED** [review]

**Comment by rh0delta** [comment]
Don't merge the PR until the release goes out, will probably be on Monday. @frankiebee can put through the release when she is online

**Comment by mixmix** [comment]
oh ... this change was a surprise for me. I'm gonna start another issue to clarify why we're doing with our CLI output, cos this is that "can I parse that easily" challenge I keep raising.

**Pull request merged**
