### PR TITLE
[NayNay] Only substrate

### LINKED ISSUE #328: Remove unnecessary instantiations of entropy instance when only substrate is used
Now that we are able to load the substrate api without instantiating an entropy instance, we should now go through and update the rest of the cli and remove the unnecessary load of the entropy instance.

### PR DESCRIPTION
**Pull request by rh0delta**
## Related Issue(s)

- Resolves #328 

## Proposed Changes

- updated trasnfer to only need substrate rather than the entire entropy instance

## Testing

- [x] Unit tests added/updated
- [ ] Integration tests added/updated
- [x] Manual testing performed

## Checklist

- [x] I have performed a self-review of my code.
- [ ] I have added tests.
- [ ] I have commented my code.
- [ ] I have included a `CHANGELOG.md` entry.
- [ ] I have updated documentation in `github.com:entropyxyz/entropy-docs`, where necessary.

### CODE REVIEW

**Review by mixmix — DISMISSED** [review]
@rh0delta can you take this PR a bit further and show what it looks like to remove `entropy` completely from `interatction` and `command`. Right now we still have `loadEntropyCLI` or `loadEntropyTUI` happening upstream and the idea I had was that instantiatioin is where errors are handled etc. I want to see the value complete and that it works and we really can get away from loading `entropy`

**Comment by mixmix** [comment]
I shoulda said this seems real promising as a path, nice observation!

**Comment by rh0delta** [comment]
> @rh0delta can you take this PR a bit further and show what it looks like to remove `entropy` completely from `interatction` and `command`. Right now we still have `loadEntropyCLI` or `loadEntropyTUI` happening upstream and the idea I had was that instantiatioin is where errors are handled etc. I want to see the value complete and that it works and we really can get away from loading `entropy`

the idea here was to remove the instantiation of entropy where we can. however, transfer still requires some data coming from the entropy instance, i.e the signer pair coming from the keyring, so we are unable to completely remove the load of entropy upstream. The most that could be done currently, is the removal of the need for the entropy instance in the class itself.

**Comment by rh0delta** [comment]
@mixmix may have found a way to completely remove entropy instance from transfer, both in TUI and CLI. please give it a re-review.

**Pull request merged**
