### PR TITLE
[NayNay] Removing Mention of Password

### LINKED ISSUE #239: remove any mention of password
We dont acctually encrypt right now so just remove all mention of it. DONT COMMENT IT OUT. Delete all comments

### PR DESCRIPTION
**Pull request by rh0delta**
## Related Issue(s)

- resolves #239 

## Proposed Changes

- removed all mentions of password encryption in the cli

## Testing

- [ ] Unit tests added/updated
- [ ] Integration tests added/updated
- [ ] Manual testing performed

## Checklist

- [x] I have performed a self-review of my code.
- [ ] I have added tests.
- [ ] I have commented my code.
- [ ] I have included a `CHANGELOG.md` entry.
- [x] I have updated documentation in `github.com:entropyxyz/entropy-docs`, where necessary.

### CODE REVIEW

**Comment by mixmix** [comment]
@rh0delta question for me here is "how sure are we that this isn't coming back?"

**Comment by rh0delta** [comment]
> @rh0delta question for me here is "how sure are we that this isn't coming back?"

I believe the intention here is to remove any mention/use of password encryption from the legacy interface. We have a new issue that is intended to track our discussions and design sessions for the new encryption flow.

**Comment by johnnymatthews** [comment]
Blocked until https://github.com/entropyxyz/entropy-docs/pull/239 is out of draft-mode.

**Comment by johnnymatthews** [comment]
Aaaaand https://github.com/entropyxyz/entropy-docs/pull/239 is ready to merge. This PR is no longer blocked by docs.

**Review by johnnymatthews — APPROVED** [review]
Looks good from where I'm stood. But get an engineer to approve this before merging.

**Comment by mixmix** [comment]
Sure, I'll approve, we can time-travel!

**Review by mixmix — APPROVED** [review]

**Pull request merged**
